#!/bin/sh
#
# specify the mailbox file you want to read on the command line
#
MAILDIR=$HOME/Mail
cd $MAILDIR
LOCKFILE=$1.lock
if lockfile -! -r1 $LOCKFILE
then
 echo Mail is currently arriving, please wait...
 while
   lockfile -! -4 -r2 $LOCKFILE
 do
 echo Mail is still arriving...
 done
fi
#
# Call you favourite mailer here.
#
/usr/ucb/mail -f $*
#
#
#
rm -f $LOCKFILE
